
(require 'color-theme)
;; twilight doesn't have a "provides" statement
(load-library "color-theme-twilight")
(load-library "color-theme-molokai")

(defun color-theme-enri ()
  "my color theme, based on the twilight one"
  (interactive)
  (color-theme-install
   '(color-theme-twilight
     ((background-color . "#141414")
      (background-mode . dark)
      (border-color . "#141414")
      (cursor-color . "gold")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "#141414" :foreground "#F8F8F8"))))
     (blue ((t (:foreground "blue"))))
     (minibuffer-prompt ((t (:foreground "#F9EE98"))))
     (italic ((t (:italic t))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (underline ((t (:underline t))))
     (border-glyph ((t (nil))))
     (link ((t (:foreground "#F9EE98"))))
     (link-visited ((t (:foreground "#D2A8A1"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (region ((t (:background "#27292A"))))
     (highlight ((t (:background "#112233"))))
                                        ;(highlight ((t (:background "#111111"))))
     (highline-face ((t (:background "SeaGreen"))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (zmacs-region ((t (:background "snow" :foreground "blue"))))
     (buffers-tab ((t (:background "#141414" :foreground "#F8F8F8"))))
     (font-lock-builtin-face ((t (:foreground "#F8F8F8"))))
     (font-lock-comment-face ((t (:italic t :foreground "#5F5A60"))))
     (font-lock-constant-face ((t (:foreground "#D2A8A1"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#F9EE98"))))
     (font-lock-keyword-face ((t (:foreground "#CDA869"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-negation-char-face ((t (:foreground "red"))))
     (font-lock-warning-face ((t (:italic t :foreground "#D2A8A1"))))
     (font-lock-type-face ((t (:foreground "#9B703F"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#8F9D6A"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6"))))
     (font-lock-warning-face ((t (:bold t :background "#EE799F" :foreground "red"))))
     ;; nxml colors (!)
     (nxml-delimiter-face ((t (:foreground "#F9EE98"))))
     (nxml-delimiter-data-face ((t (:foreground "#4A410D"))))
     (nxml-name-face ((t (:foreground "#CDA869"))))
     (nxml-ref-face ((t (:foreground "#CF6A4C"))))
     (nxml-text-face ((t (:foreground "#F8F8F8"))))
     (nxml-comment-content-face ((t (:italic t :foreground "#7587A6"))))
     (nxml-comment-delimiter-face ((t (:italic t :foreground "#7587A6"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#8996A8"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#8996A8"))))
     (nxml-processing-instruction-content-face ((t (:foreground "#8996A8"))))
     ;;     (nxml-cdata-section-delimiter-face ((t (:foreground "red"))))
     ;;    (nxml-cdata-section-cdata-face ((t (:foreground "red"))))
     (nxml-cdata-section-content-face ((t (:italic t))))
     ;;     (nxml-char-ref-number-face ((t (:foreground "red"))))
     ;;     (nxml-char-ref-delimiter-face ((t (:foreground "red"))))
     ;;     (nxml-tag-delimiter-face ((t (:foreground "red"))))
     ;;     (nxml-tag-slash-face ((t (:foreground "red"))))
     ;;     (nxml-name-element-prefix-face ((t (:foreground "red"))))
     ;;     (nxml-name-element-colon-face ((t (:foreground "red"))))
     ;;     (nxml-name-element-local-name-face ((t (:foreground "red"))))
     (nxml-attribute-prefix-face ((t (:foreground "red"))))
     (nxml-attribute-local-name-face ((t (:foreground  "#8F9D6A"))))
     ;;      (nxml-attribute-xmlns-face ((t (:foreground "red"))))
     ;;     (nxml-attribute-colon-face ((t (:foreground "red"))))
     ;;     (nxml-attribute-prefix-face ((t (:foreground "red"))))
     ;;     (nxml-attribute-value-face ((t (:foreground "#CF6A4C"))))
     ;;     (nxml-attribute-value-delimiter-face ((t (:foreground "red"))))
     ;;     (nxml-namespace-attribute-value-face ((t (:foreground "#9B859D"))))
     ;;     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "#9B859D"))))
     ;;     (nxml-prolog-literal-delimiter-face ((t (:foreground "red"))))
     ;;     (nxml-prolog-literal-content-face ((t (:foreground "red"))))
     ;;     (nxml-prolog-keyword-face ((t (:foreground "red"))))
     ;;     (nxml-markup-declaration-delimiter-face ((t (:foreground "red"))))
     ;;     (nxml-hash-face ((t (:foreground "red"))))
     ;;     (nxml-glyph-face ((t (:foreground "red"))))
     ;; end nxml colors
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (show-paren-match-face ((t (:background "#F8F8F8" :foreground "#141414"))))
     (custom-state ((((class color) (background dark)) (:foreground "forestgreen"))))
     (variable-pitch ((t (:family "verdana"))))
     ;; info
     ;;      (info-header-node ((t (:foreground "#666"))))
                                        ;      (info-header-xref ((t (:foreground "#666"))))
     ;;      (info-menu-5 ((t (:underline t))))
     ;;      (info-menu-header ((t (:bold t :foreground "#666"))))
     ;;     (info-node ((t (:foreground "#F9EE98"))))
     ;;      (info-xref ((t (:bold t :foreground "#777"))))
     )))

(color-theme-molokai)

(message "Colors loaded!")

(provide 'es-colors)
